# Challenge 1

In this challenge you will be working on **Pokemon**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](../images/pokemon.jpg)

Follow the instructions below and enter your code.

#### Import all required libraries.

In [11]:
# import libraries
import pandas as pd
import numpy as np
import re

#### Import data set.

Read the dataset `pokemon.csv` into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [12]:
# import dataset
pokemon=pd.read_csv('pokemon.csv')
pokemon=pd.DataFrame(pokemon)

#### Print first 10 rows of `pokemon`.

In [13]:
# your code here
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

#### Obtain the distinct values across `Type 1` and `Type 2`.

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [14]:
#Append to type1 the values from type 2 and give me only the unique values

# your code here
uniqueValues = (pokemon['Type 1'].append(pokemon['Type 2'])).unique()

print (uniqueValues)

['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying' nan]

In [15]:
#visualize wrong names
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Cleanup `Name` that contain "Mega".

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [16]:
# Regex changes from the column names, and uses apply to pass a lambda function that substitues anything before mega
#and is replaced for nothing:

pokemon['Name'] = pokemon['Name'].apply(lambda x: re.sub('.+?(?=Mega)','',x))
pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

#### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`.

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [17]:
# your code here
pokemon['A/D Ratio']=pokemon['Attack']/pokemon['Defense']

pokemon.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462

#### Identify the pokemon with the highest `A/D Ratio`.

In [18]:
# your code here
pokemon[pokemon['A/D Ratio']==pokemon['A/D Ratio'].max()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

#### Identify the pokemon with the lowest A/D Ratio.

In [19]:
# your code here
pokemon[pokemon['A/D Ratio']==pokemon['A/D Ratio'].min()]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
230,213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

#### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [34]:
# your code here

#How it works numpy.where? -> np.where(if 1, result 1, otherwise result 2)
pokemon['Combo Type']=np.where(pokemon['Type 2'].isnull() , pokemon['Type 1'], pokemon['Type 1'] +'-'+pokemon['Type 2'])

pokemon.head(30)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,1.209302,Fire
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,1.103448,Fire
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,1.076923,Fire-Flying
7,6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,1.171171,Fire-Dragon
8,6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,1.333333,Fire-Flying
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,0.738462,Water
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,0.787500,Water
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,0.830000,Water
12,9,Mega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,0.858333,Water
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False,0.857143,Bug
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,0.363636,Bug
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False,0.900000,Bug-Flying
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,1.166667,Bug-Poison
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,0.500000,Bug-Poison
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,2.250000,Bug-Poison
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750000,Bug-Poison
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False,1.125000,Normal-Flying
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False,1.090909,Normal-Flying
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False,1.066667,Normal-Flying
23,18,Mega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,1.000000,Normal-Flying
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False,1.600000,Normal
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False,1.350000,Normal
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False,2.000000,Normal-Flying
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False,1.384615,Normal-Flying
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False,1.363636,Poison
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False,1.231884,Poison
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False,1.375000,Electric
31,26,Raichu,Electric,NaN,485,60,90,55,90,80,110,1,False,1.636364,Electric
32,27,Sandshrew,Ground,NaN,300,50,75,85,20,30,40,1,False,0.882353,Ground
33,28,Sandslash,Ground,NaN,450,75,100,110,45,55,65,1,False,0.909091,Ground
34,29,Nidoran♀,Poison,NaN,275,55,47,52,40,40,41,1,False,0.903846,Poison
35,30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,1,False,0.925373,Poison
36,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False,1.057471,Poison-Ground
37,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False,1.425000,Poison
38,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False,1.263158,Poison
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False,1.324675,Poison-Ground
40,35,Clefairy,Fairy,NaN,323,70,45,48,60,65,35,1,False,0.937500,Fairy
41,36,Clefable,Fairy,NaN,483,95,70,73,95,90,60,1,False,0.958904,Fairy
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False,1.025000,Fire
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False,1.013333,Fire
44,39,Jigglypuff,Normal,Fairy,270,115,45,20,45,25,20,1,False,2.250000,Normal-Fairy
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False,1.555556,Normal-Fairy
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False,1.285714,Poison-Flying
47,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False,1.142857,Poison-Flying
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False,0.909091,Grass-Poison
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False,0.928571,Grass-Poison
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False,0.941176,Grass-Poison
51,46,Paras,Bug,Grass,285,35,70,55,45,55,25,1,False,1.272727,Bug-Grass
52,47,Parasect,Bug,Grass,405,60,95,80,60,80,30,1,False,1.187500,Bug-Grass
53,48,Venonat,Bug,Poison,305,60,55,50,40,55,45,1,False,1.100000,Bug-Poison
54,49,Venomoth,Bug,Poison,450,70,65,60,90,75,90,1,False,1.083333,Bug-Poison
55,50,Diglett,Ground,NaN,265,10,55,25,35,45,95,1,False,2.200000,Ground
56,51,Dugtrio,Ground,NaN,405,35,80,50,50,70,120,1,False,1.600000,Ground
57,52,Meowth,Normal,NaN,290,40,45,35,40,40,90,1,False,1.285714,Normal
58,53,Persian,Normal,NaN,440,65,70,60,65,65,115,1,False,1.166667,Normal

#### Identify the pokemon whose `A/D Ratio` are among the top 5.

In [22]:
# your code here
df=pokemon.sort_values(by=['A/D Ratio'],ascending=False).head(5)
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,NaN,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

#### For the 5 pokemon printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemon with the highest `A/D Ratio`.

In [23]:
# your code here
unique_combo_type = df['Combo Type'].unique()

print (unique_combo_type)

['Psychic' 'Water-Dark' 'Bug-Poison' 'Rock']

#### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemon.

Your output should look like below:

![Aggregate](../images/aggregated-mean.png)

In [27]:
# your code here

#Step 1: group by compbo type and apply agg funtion mean. Then show result
df1=pokemon.groupby(by='Combo Type',as_index=False).agg('mean')
df1.head(10)

,Combo Type,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,Bug,361.352941,289.705882,53.058824,50.352941,55.411765,39.294118,43.647059,47.941176,3.470588,0.0,0.940179
1,Bug-Electric,595.500000,395.500000,60.000000,62.000000,55.000000,77.000000,55.000000,86.500000,5.000000,0.0,1.111667
2,Bug-Fighting,214.000000,550.000000,80.000000,155.000000,95.000000,40.000000,100.000000,80.000000,2.000000,0.0,1.637681
3,Bug-Fire,636.500000,455.000000,70.000000,72.500000,60.000000,92.500000,80.000000,80.000000,5.000000,0.0,1.234266
4,Bug-Flying,286.285714,419.500000,63.000000,70.142857,61.571429,72.857143,69.071429,82.857143,2.857143,0.0,1.146274
5,Bug-Ghost,292.000000,236.000000,1.000000,90.000000,45.000000,30.000000,30.000000,40.000000,3.000000,0.0,2.000000
6,Bug-Grass,354.833333,384.000000,55.000000,73.833333,76.666667,57.333333,76.666667,44.500000,3.500000,0.0,0.983165
7,Bug-Ground,351.500000,345.000000,45.500000,62.000000,97.500000,44.500000,57.500000,38.000000,3.500000,0.0,0.626190
8,Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.0,1.315989
9,Bug-Rock,442.666667,435.000000,46.666667,56.666667,146.666667,36.666667,113.333333,35.000000,4.000000,0.0,0.522728

In [28]:
#name result to the subset with the combotypes from previous exercise
result=df1[(df1['Combo Type']=='Bug-Poison') + (df1['Combo Type']=='Psychic') + (df1['Combo Type']=='Rock') + (df1['Combo Type']=='Water-Dark')]
result.head(10)

C:\Users\x250\Anaconda3\lib\site-packages\pandas\core\computation\expressions.py:178: UserWarning: evaluating in Python space because the '+' operator is not supported by numexpr for the bool dtype, use '|' instead
  f"evaluating in Python space because the {repr(op_str)} "

,Combo Type,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
8,Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
109,Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196
117,Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091
140,Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949

In [29]:
#Pretty print
result.set_index('Combo Type')

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,,
Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
Psychic,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196
Rock,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091
Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949